SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[VProducto]
AS
    SELECT 
        PR.IDPRO AS 'IDPRO',
        PR.NOMPRO AS 'NOMPRO',
		PR.PREPRO AS 'PREPRO',
        PR.DESPRO AS 'DESPRO',
        PR.TIPPRO AS 'TIPPRO',
        PR.ESTPRO AS 'ESTPRO',
        CONCAT(PV.RAZSOCPROV, ', ', PV.RUCPROV) AS 'PROVEEDOR',
        ROW_NUMBER() OVER (ORDER BY PR.IDPRO DESC) AS ORDEN
    FROM 
        PRODUCTO AS PR
        INNER JOIN PROVEEDOR AS PV on
        PR.IDPROV = PV.IDPROV
GO
