CREATE TABLE [dbo].[PRODUCTO]
(
[IDPRO] [int] NOT NULL IDENTITY(1, 1),
[TIPPRO] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[NOMPRO] [varchar] (100) COLLATE Modern_Spanish_CI_AS NOT NULL,
[PREPRO] [decimal] (10, 2) NOT NULL,
[DESPRO] [varchar] (100) COLLATE Modern_Spanish_CI_AS NOT NULL,
[ESTPRO] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL,
[IDPROV] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCTO] ADD CONSTRAINT [PRODUCTO_pk] PRIMARY KEY CLUSTERED  ([IDPRO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCTO] ADD CONSTRAINT [PRODUCTO_PROVEDOR] FOREIGN KEY ([IDPROV]) REFERENCES [dbo].[PROVEEDOR] ([IDPROV])
GO
