CREATE TABLE [dbo].[UBIGEO]
(
[CODUBI] [char] (6) COLLATE Modern_Spanish_CI_AS NOT NULL,
[PROUBI] [varchar] (150) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DEPUBI] [varchar] (150) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DISUBI] [varchar] (150) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[UBIGEO] ADD CONSTRAINT [UBIGEO_pk] PRIMARY KEY CLUSTERED  ([CODUBI]) ON [PRIMARY]
GO
