CREATE TABLE [dbo].[VENDEDOR]
(
[IDVEND] [int] NOT NULL IDENTITY(1, 1),
[DNIVEND] [char] (8) COLLATE Modern_Spanish_CI_AS NOT NULL,
[NOMVEND] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[APEVEND] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CELVEND] [char] (8) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DIRVEND] [varchar] (100) COLLATE Modern_Spanish_CI_AS NOT NULL,
[EMAVEND] [varchar] (100) COLLATE Modern_Spanish_CI_AS NOT NULL,
[ESTVEND] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CODUBI] [char] (6) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENDEDOR] ADD CONSTRAINT [VENDEDOR_pk] PRIMARY KEY CLUSTERED  ([IDVEND]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENDEDOR] ADD CONSTRAINT [VENDEDOR_UBIGEO] FOREIGN KEY ([CODUBI]) REFERENCES [dbo].[UBIGEO] ([CODUBI])
GO
